name: .NET Core

on: [push]

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.dotnet }}
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - name: Getting code
      uses: actions/checkout@v1
          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Build
      run: dotnet build --configuration Release --nologo
      
    - name: Try Publish(if the version has changed) WixSharp.DotNetBootstrapper
      run: dotnet nuget push src\WixSharp.DotNetBootstrapper\bin\Release\WixSharp.DotNetBootstrapper.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json; exit 0
      
    - name: Try Publish(if the version has changed) WixSharp.DotNetBootstrapper.Web
      run: dotnet nuget push src\WixSharp.DotNetBootstrapper.Web\bin\Release\WixSharp.DotNetBootstrapper.Web.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json; exit 0
